version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      DATABASE_NAME: postgres
  app:
    image: alelitvinov/devops-for-programmers-project-lvl1
    build:
        context: .
        dockerfile: Dockerfile.production
    command: bash -c 'sleep 5 && npm test'
    depends_on:
      - db
